name: TestCoverage Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Test
        uses: actions/checkout@v2

      - name: Build and Test
        run: xcodebuild test -project CodecovDemo.xcodeproj -scheme CodecovDemo -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' build test
